version: 2
jobs:
  build:

    docker:
      - image: python:3.7
        environment:
          MPLBACKEND: "agg"

    steps:
      - checkout

      - run:
          name: install gmsh
          command: |
            wget http://gmsh.info/bin/Linux/gmsh-git-Linux64.tgz
            tar xzf gmsh-git-Linux64.tgz
            apt-get update
            apt-get install -y libglu1-mesa
            cp gmsh-git-Linux64/bin/gmsh /usr/local/bin

      - run:
          name: flake8 tests
          command: |
            pip3 install flake8
            python3 -m flake8 minidolfin

      - run:
          name: Install minidolfin
          command: |
            pip3 install -r requirements.txt
            pip3 install .

      - run:
          name: Environment and FFC version info
          command: |
            echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
            python3 -c'import ffc, ffc.git_commit_hash; \
                print(ffc.git_commit_hash.git_commit_hash())'

      - run:
          name: Test demo (JIT)
          command: |
            cd demo
            python3 helmholtz.py -d -n 4
            python3 mesh_demo.py
            python3 elasticity.py
            python3 gmsh_demo.py
#            python3 helmholtz.py -d -n 4 -c tsfc -f mode=spectral
#            python3 helmholtz.py -d -n 4 -c tsfc -f mode=vanilla
#            python3 helmholtz.py -d -n 4 -c tsfc -f mode=tensor
#            python3 helmholtz.py -d -n 4 -c ffc -r uflacs -f enable_preintegration=1
#            python3 helmholtz.py -d -n 4 -c ffc -r uflacs -f enable_preintegration=0
#            python3 helmholtz.py -d -n 4 -c ffc -r tsfc -f mode=vanilla
#            python3 helmholtz.py -d -n 4 -c ffc -r tsfc -f mode=spectral
